spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # 첫 배포 이후 validate 으로 수정

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            redirectUri: "myapp://home"
            scope:
              - profile_nickname
              - profile_image
            clientName: Kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

jwt:
  key: ${JWT_SECRET_KEY}

openai:
  api-key: ${OPENAI_API_KEY}
  url: ${OPENAI_URL}